-- Messages of a Project's Conversation, oldest first. `id` is a UUIDv7 generated by the API, so it
-- also orders messages by creation.
create table public.messages (
  id         uuid primary key,
  project_id uuid not null references public.projects (id) on delete cascade,
  role       text not null check (role in ('user', 'assistant')),
  body       text not null check (char_length(body) between 1 and 20000),
  created_at timestamptz not null default now()
);

create index messages_project_id_id_idx on public.messages (project_id, id);

alter table public.messages enable row level security;
